### ISSUE TITLE
[FEATURE] Add CW API request metrics that match API billing

### ISSUE THREAD

**Issue by vainiusd** [nerdswords/yet-another-cloudwatch-exporter#1233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

AWS bills YACE generated requests differently based on CW API requests.

CW ListMetrics -> for # of requests. This metric is not present in current YACE natively exported metrics.
CW GetMetricData -> for # of metrics retrieved. Currently YACE natively exports only the count of this API requests.

This would help to make the "price" of YACE exported metrics more accountable.

I suggest adding these metrics to the list of exported ones.

**Comment by JDuskey** [comment]
The GetMetricData issue has been reported (and implemented by linked PRs) in #339
I think with that implementation though it would be nice to see which namespaces are requesting the most data as a label on the metric to make debugging easier.

The ListMetrics one I can make a PR for.

**Comment by kgeckhart** [comment]
👋 thanks for adding these metrics I think it will be helpful! I was just wondering if you have a source for this line,

> CW GetMetricData -> for # of metrics retrieved. Currently YACE natively exports only the count of this API requests.

because the CloudWatch pricing docs seem to indicate it's related to requested data and I'm not able to find anything that says it's about returned data, https://aws.amazon.com/cloudwatch/pricing/?nc1=h_ls. 

> GetMetricData, GetInsightRuleReport	$0.01 per 1,000 metrics requested

If there is somewhere in AWS's docs which says "requested" = "returned" I think it would be awesome to have that linked to prevent confusion.
