### ISSUE TITLE
Bug: Option nilToZero is ignored

### ISSUE THREAD

**Issue by daviddetorres** [nerdswords/yet-another-cloudwatch-exporter#170]
The config option nilToZero is being ignored.

Reported in #151

**Comment by shubhamc183** [comment]
@daviddetorres is anyone working on this?

Can you point me how can it be solved? I'll try to send a PR!

TIA

**Comment by daviddetorres** [comment]
This is trickier than it seems at first sight.

The point is that if a metric has not a value for a combination of labels (nil), should it have it, or they really don't exist?

Example: 
- You have a metric for an error that has a numerical value if >0 but does not return a value if the value is 0 (this is typical in cloudwatch).
- Imagine now that the resource that generates the metric dissapears (because you remove it). The effect is the same: you do not have value for that metric. Should it be 0? or nil?

Another example: 
- You have 300 S3 buckets, but you only configure the hourly metrics in 10 of them. 
- Should all the other 290 will generate metrics =0?

How are we addressing this 'no data if 0'? Normally they are for errors, so for alerting, you will have something like `error_metric > 0`, so it works fine. 
For panels and dashboards we are using the option of `metric_error{filter="whatever"} or vector(0)`. This will fill with `0` the metrics with data in the graphic and will leave no gaps.

If you really want to implement it, you will have to: 
- Gather all possible combination of that should have data (beware that for ALB this can be tricky because of the target groups). 
- Detect that  each of the combination of labels that should have data, actually have.
- If any of them has not data, add 0 as value.   

The complex part IMHO is how to make in a consistent way the combination of labels that should have data. Any idea on how to make it easy and coherent across all the AWS services?

**Comment by nhinds** [comment]
In 0.15.0 and earlier, yace used to [detect the dimensions to query automatically](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.15.0-alpha/abstract.go#L151), [fill in any unknowns by querying `ListMetrics` if required](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.15.0-alpha/aws_cloudwatch.go#L359), and eventually [call GetMetricData based on those dimensions](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.15.0-alpha/abstract.go#L208), then [coerce any nil or missing values in those results to zero](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.15.0-alpha/aws_cloudwatch.go#L598-L601).

In my opinion, `nilToZero` should produce a `0` value in all of the cases that it used to produce a `0` value in version 0.15.0 and earlier -- that is, produce a `0` for all dimensions that [`detectDimensionsByService` and `getMetricsList` used to return](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.15.0-alpha/aws_cloudwatch.go#L399)

It appears that [`detectDimensionsByService` still exists](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/aws_cloudwatch.go#L466), and [we still call `ListMetrics`](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/abstract.go#L173), so it should theoretically be possible to combine this information with the retrieved data and add the zero values back in.


> Imagine now that the resource that generates the metric dissapears (because you remove it). The effect is the same: you do not have value for that metric. Should it be 0? or nil?

In the case where a resource has been deleted, it will not appear in the [response from the resource groups tagging API when filtering by tags](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/abstract.go#L226), so it will not be passed into `getMetricDataForQueries` as one of the resources to query by, and it should not be returned from the exporter.

>     You have 300 S3 buckets, but you only configure the hourly metrics in 10 of them.
>     Should all the other 290 will generate metrics =0?

Yes please. This is the previous behaviour; since my scrape configuration said to generate the metrics for all S3 buckets with certain tags and use `0` for missing values, it is nice to have the metrics be present for all of those buckets.

I wouldn't be hugely upset if it changed to only return `0` for buckets with the configuration enabled, but it seems difficult to tell this from the resource groups tagging API and cloudwatch metrics alone, so returning a `0` for all matching resources when `nilToZero` is specified seems the most straightforward approach. Since users have to opt into this setting for each metric configuration anyway, it shouldn't be too surprising that `0` values appear for the metrics.

**Comment by thomaspeitz** [comment]
Fixed and released
