### ISSUE TITLE
[BUG] Github latest release no longer tracks the alpha release

### ISSUE THREAD

**Issue by Rumbles** [nerdswords/yet-another-cloudwatch-exporter#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I checked the github api for the latest release of yace and it is no longer the alpha release, instead it is the helm chart...

Until three days ago it was normally the most recent alpha release, is this an intentional change? I believe the latest release by date is marked as latest, but there is a subsequent release of the alpha that isn't marked as latest.

Was this an intentional change?

### Expected Behavior

Latest release should point to https://github.com/nerdswords/yet-another-cloudwatch-exporter/releases/tag/v0.46.0-alpha as far as I understand it

### Steps To Reproduce

N/A github config

**Comment by cristiangreco** [comment]
Hi @Rumbles thanks for the bug report. This is not exactly intentional. We now release both yace binaries and the helm chart. With the current setup the helm chart release might come after binaries release, that's why you see it as latest.

I'll look into the GH actions to make sure the binaries release is latest.

**Comment by cristiangreco** [comment]
This is fixed now since the helm chart has been moved to https://github.com/nerdswords/helm-charts
