### ISSUE TITLE
[BUG] AWS GOV FIPS endpoint misconfiguration

### ISSUE THREAD

**Issue by jku-s1** [nerdswords/yet-another-cloudwatch-exporter#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.51.0

### Config file

config: |-
  apiVersion: v1alpha1
  sts-region: us-gov-west-1
  discovery:
    exportedTagsOnMetrics:
      ec2:
        - KubernetesCluster
      ebs:
        - KubernetesCluster
        - kubernetes.io/created-for/pvc/name
        - kubernetes.io/created-for/pvc/namespace
    jobs:
    - type: ebs
      regions:
        - us-gov-west-1
      searchTags:
        - key: KubernetesCluster
          value: .*stage.*
      metrics:
        - name: VolumeIdleTime
          statistics:
          - Sum
          - Minimum
          - Maximum
          - Average

### Current Behavior

Hi, I try to enable `--fips` to contact the AWS GOV sts endpoint and figure out that it doesn't work because AWS GOV currently not use `sts-fips.<region>.amazonaws.com` pattern. And also I would like to ask when I enable the FIPS if the exporter use the FIPS endpoints also for example for tagging API etc.

### Expected Behavior

Contact the right endpoint in AWS GOV.

https://aws.amazon.com/compliance/fips/

AWS Security Token Service (STS) | sts-fips.us-east-1.amazonaws.com sts-fips.us-east-2.amazonaws.com sts-fips.us-west-1.amazonaws.com sts-fips.us-west-2.amazonaws.com | sts.us-gov-east-1.amazonaws.com sts.us-gov-west-1.amazonaws.com
-- | -- | --

### Anything else?

`{"arn":"","error":"RequestError: send request failed\ncaused by: Post \"https://sts-fips.us-gov-west-1.amazonaws.com/\": dial tcp: lookup sts-fips.us-gov-west-1.amazonaws.com on 100.64.0.10:53: no such host","job_type":"ebs","level":"error","msg":"Couldn't get account Id","region":"us-gov-west-1","time":"2023-05-16T14:15:48Z"}`

**Comment by kgeckhart** [comment]
👋 @jku-s1 there was another issue opened regarding FIPS support in aws sdk v2, https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/966. Based on [AWS compliance docs](https://aws.amazon.com/compliance/fips/) they don't have FIPS endpoints for AutoScaling API and Tagging API. 

The current implementation in YACE uses hard coded URLs for FIPS endpoints and that logic could be change so that sts works for the use case you have. But I was wondering if YACE would work for you in a FIPS scenario if it's calling AWS endpoints which are not FIPS compliant.

**Comment by cristiangreco** [comment]
Fixed by https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/1108
